cd ./external_scripts/meme
rm -r ./meme_output
mkdir ./meme_output
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LAFLPLATPVSDAKVLTGRQKPLTEVAIII consolidated.fasta &>>./meme_output/meme_out0.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GDRIEWVKLSLAFLPLATPVSDAKVLTGRQ consolidated.fasta &>>./meme_output/meme_out1.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons SDAKVLTGRQKPLTEVAIIIAEIRSRDGFE consolidated.fasta &>>./meme_output/meme_out2.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons TEVAIIIAEIRSRDGFEGVGFSYSKRAGGQ consolidated.fasta &>>./meme_output/meme_out3.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons TGRQKPLTEVAIIIAEIRSRDGFEGVGFSY consolidated.fasta &>>./meme_output/meme_out4.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons AEIRSRDGFEGVGFSYSKRAGGQGIYAHAK consolidated.fasta &>>./meme_output/meme_out5.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons IADNLLGEDPNDIDKIYTKLLWAGASVGRS consolidated.fasta &>>./meme_output/meme_out6.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GVGFSYSKRAGGQGIYAHAKEIADNLLGED consolidated.fasta &>>./meme_output/meme_out7.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons WAGASVGRSGMAVQAISPIDIALWDMKAKR consolidated.fasta &>>./meme_output/meme_out8.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons SPIDIALWDMKAKRAGLPLAKLLGAHRDSV consolidated.fasta &>>./meme_output/meme_out9.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GMAVQAISPIDIALWDMKAKRAGLPLAKLL consolidated.fasta &>>./meme_output/meme_out10.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons WDMKAKRAGLPLAKLLGAHRDSVQCYNTSG consolidated.fasta &>>./meme_output/meme_out11.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons YNTSGGFLHTPLDQVLKNVVISRENGIGGI consolidated.fasta &>>./meme_output/meme_out12.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LAKLLGAHRDSVQCYNTSGGFLHTPLDQVL consolidated.fasta &>>./meme_output/meme_out13.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons VLKNVVISRENGIGGIKLAVGQPNCAEDIR consolidated.fasta &>>./meme_output/meme_out14.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GQPNCAEDIRRLTAVREALGDEFPLMVDAN consolidated.fasta &>>./meme_output/meme_out15.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons ISRENGIGGIKLAVGQPNCAEDIRRLTAVR consolidated.fasta &>>./meme_output/meme_out16.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons VREALGDEFPLMVDANQQWDRETAIRMGRK consolidated.fasta &>>./meme_output/meme_out17.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons NQQWDRETAIRMGRKMEQFNLIWIEEPLDA consolidated.fasta &>>./meme_output/meme_out18.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons EALGDEFPLMVDANQQWDRETAIRMGRKME consolidated.fasta &>>./meme_output/meme_out19.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons RKMEQFNLIWIEEPLDAYDIEGHAQLAAAL consolidated.fasta &>>./meme_output/meme_out20.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons QFNLIWIEEPLDAYDIEGHAQLAAALDTPI consolidated.fasta &>>./meme_output/meme_out21.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons IRMGRKMEQFNLIWIEEPLDAYDIEGHAQL consolidated.fasta &>>./meme_output/meme_out22.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons EPLDAYDIEGHAQLAAALDTPIATGEMLTS consolidated.fasta &>>./meme_output/meme_out23.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons QLAAALDTPIATGEMLTSFREHEQLILGNA consolidated.fasta &>>./meme_output/meme_out24.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons WIEEPLDAYDIEGHAQLAAALDTPIATGEM consolidated.fasta &>>./meme_output/meme_out25.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LTSFREHEQLILGNASDFVQPDAPRVGGIS consolidated.fasta &>>./meme_output/meme_out26.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons QPDAPRVGGISPFLKIMDLAAKHGRKLAPH consolidated.fasta &>>./meme_output/meme_out27.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons EHEQLILGNASDFVQPDAPRVGGISPFLKI consolidated.fasta &>>./meme_output/meme_out28.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons KIMDLAAKHGRKLAPHFAMEVHLHLSAAYP consolidated.fasta &>>./meme_output/meme_out29.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GRKLAPHFAMEVHLHLSAAYPLEPWLEHFE consolidated.fasta &>>./meme_output/meme_out30.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LKIMDLAAKHGRKLAPHFAMEVHLHLSAAY consolidated.fasta &>>./meme_output/meme_out31.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons EVHLHLSAAYPLEPWLEHFEWLNPLFNEQL consolidated.fasta &>>./meme_output/meme_out32.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons PLFNEQLELRDGRMWISDRHGLGFTLSEQA consolidated.fasta &>>./meme_output/meme_out33.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LEPWLEHFEWLNPLFNEQLELRDGRMWISD consolidated.fasta &>>./meme_output/meme_out34.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons RMWISDRHGLGFTLSEQARRWTQLTCEFGK consolidated.fasta &>>./meme_output/meme_out35.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons KITDLELHAVGIPRHTGFVNKHVIVKIHTD consolidated.fasta &>>./meme_output/meme_out36.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons MKITDLELHAVGIPRHTGFVNKHVIVKIHT consolidated.fasta &>>./meme_output/meme_out37.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons HTGFVNKHVIVKIHTDEGLTGIGEMSDFSH consolidated.fasta &>>./meme_output/meme_out38.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons FVNKHVIVKIHTDEGLTGIGEMSDFSHLPL consolidated.fasta &>>./meme_output/meme_out39.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GIPRHTGFVNKHVIVKIHTDEGLTGIGEMS consolidated.fasta &>>./meme_output/meme_out40.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons VKIHTDEGLTGIGEMSDFSHLPLYSVDLHD consolidated.fasta &>>./meme_output/meme_out41.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GEMSDFSHLPLYSVDLHDLKQGLLSILLGQ consolidated.fasta &>>./meme_output/meme_out42.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons KHVIVKIHTDEGLTGIGEMSDFSHLPLYSV consolidated.fasta &>>./meme_output/meme_out43.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons DLKQGLLSILLGQNPFDLMKINKELTDNFP consolidated.fasta &>>./meme_output/meme_out44.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LMKINKELTDNFPETMYYFEKGSFIRNGID consolidated.fasta &>>./meme_output/meme_out45.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons DLKQGLLSILLGQNPFDLMKINKELTDNFP consolidated.fasta &>>./meme_output/meme_out46.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons FEKGSFIRNGIDNALHDLCAKYLDISVSDF consolidated.fasta &>>./meme_output/meme_out47.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons NGIDNALHDLCAKYLDISVSDFLGGRVKEK consolidated.fasta &>>./meme_output/meme_out48.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons EKGSFIRNGIDNALHDLCAKYLDISVSDFL consolidated.fasta &>>./meme_output/meme_out49.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons HDLCAKYLDISVSDFLGGRVKEKIKVCYPI consolidated.fasta &>>./meme_output/meme_out50.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons YPIFRHRFSEEVESNLDVVRQKLEQGFDVF consolidated.fasta &>>./meme_output/meme_out51.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons SDFLGGRVKEKIKVCYPIFRHRFSEEVESN consolidated.fasta &>>./meme_output/meme_out52.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LDVVRQKLEQGFDVFRLYVGKNLDADEEFL consolidated.fasta &>>./meme_output/meme_out53.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons YVGKNLDADEEFLSRVKEEFGSRVRIKSYD consolidated.fasta &>>./meme_output/meme_out54.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons VRQKLEQGFDVFRLYVGKNLDADEEFLSRV consolidated.fasta &>>./meme_output/meme_out55.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons VKEEFGSRVRIKSYDFSHLLNWKDAHRAIK consolidated.fasta &>>./meme_output/meme_out56.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons IKSYDFSHLLNWKDAHRAIKRLTKYDLGLE consolidated.fasta &>>./meme_output/meme_out57.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LSRVKEEFGSRVRIKSYDFSHLLNWKDAHR consolidated.fasta &>>./meme_output/meme_out58.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons AHRAIKRLTKYDLGLEMIESPAPRNDFDGL consolidated.fasta &>>./meme_output/meme_out59.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons DLGLEMIESPAPRNDFDGLYQLRLKTDYPI consolidated.fasta &>>./meme_output/meme_out60.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons AIKRLTKYDLGLEMIESPAPRNDFDGLYQL consolidated.fasta &>>./meme_output/meme_out61.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons SPAPRNDFDGLYQLRLKTDYPISEHVWSFK consolidated.fasta &>>./meme_output/meme_out62.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons YQLRLKTDYPISEHVWSFKQQQEMIKKDAI consolidated.fasta &>>./meme_output/meme_out63.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons MIESPAPRNDFDGLYQLRLKTDYPISEHVW consolidated.fasta &>>./meme_output/meme_out64.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons VWSFKQQQEMIKKDAIDIFNISPVFIGGLT consolidated.fasta &>>./meme_output/meme_out65.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons IFNISPVFIGGLTSAKKAAYAAEVASKDVV consolidated.fasta &>>./meme_output/meme_out66.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons KQQQEMIKKDAIDIFNISPVFIGGLTSAKK consolidated.fasta &>>./meme_output/meme_out67.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons AKKAAYAAEVASKDVVLGTTQELSVGTAAM consolidated.fasta &>>./meme_output/meme_out68.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons TQELSVGTAAMAHLGCSLTNINHTSDPTGP consolidated.fasta &>>./meme_output/meme_out69.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons AAEVASKDVVLGTTQELSVGTAAMAHLGCS consolidated.fasta &>>./meme_output/meme_out70.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GCSLTNINHTSDPTGPELYVGDVVKNRVTY consolidated.fasta &>>./meme_output/meme_out71.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons INHTSDPTGPELYVGDVVKNRVTYKDGYLY consolidated.fasta &>>./meme_output/meme_out72.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LGCSLTNINHTSDPTGPELYVGDVVKNRVT consolidated.fasta &>>./meme_output/meme_out73.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons TGPELYVGDVVKNRVTYKDGYLYAPDRSVK consolidated.fasta &>>./meme_output/meme_out74.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons DVVKNRVTYKDGYLYAPDRSVKGLGIELDE consolidated.fasta &>>./meme_output/meme_out75.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons TSDPTGPELYVGDVVKNRVTYKDGYLYAPD consolidated.fasta &>>./meme_output/meme_out76.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LYAPDRSVKGLGIELDESLLAKYQVPDLSW consolidated.fasta &>>./meme_output/meme_out77.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons DQRAIKKGAGHDGFTYTGSTVTEGFTQVRQ consolidated.fasta &>>./meme_output/meme_out78.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons KIVDVLCTPGLTGFYFDDQRAIKKGAGHDG consolidated.fasta &>>./meme_output/meme_out79.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GSTVTEGFTQVRQKGESISVLLVLEDGQVA consolidated.fasta &>>./meme_output/meme_out80.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons RQKGESISVLLVLEDGQVAHGDCAAVQYSG consolidated.fasta &>>./meme_output/meme_out81.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons TEGFTQVRQKGESISVLLVLEDGQVAHGDC consolidated.fasta &>>./meme_output/meme_out82.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons SVLLVLEDGQVAHGDCAAVQYSGAGGRDPL consolidated.fasta &>>./meme_output/meme_out83.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons QVAHGDCAAVQYSGAGGRDPLFLAKDFIPV consolidated.fasta &>>./meme_output/meme_out84.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LLVLEDGQVAHGDCAAVQYSGAGGRDPLFL consolidated.fasta &>>./meme_output/meme_out85.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons AAVQYSGAGGRDPLFLAKDFIPVIEKEIAP consolidated.fasta &>>./meme_output/meme_out86.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons EKEIAPKLIGREITNFKPMAEEFDKMTVNG consolidated.fasta &>>./meme_output/meme_out87.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons PLFLAKDFIPVIEKEIAPKLIGREITNFKP consolidated.fasta &>>./meme_output/meme_out88.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons TNFKPMAEEFDKMTVNGNRLHTAIRYGITQ consolidated.fasta &>>./meme_output/meme_out89.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons KPMAEEFDKMTVNGNRLHTAIRYGITQAIL consolidated.fasta &>>./meme_output/meme_out90.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GREITNFKPMAEEFDKMTVNGNRLHTAIRY consolidated.fasta &>>./meme_output/meme_out91.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons DKMTVNGNRLHTAIRYGITQAILDAVAKTR consolidated.fasta &>>./meme_output/meme_out92.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons YGITQAILDAVAKTRKVTMAEVIRDEYNPG consolidated.fasta &>>./meme_output/meme_out93.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons RLHTAIRYGITQAILDAVAKTRKVTMAEVI consolidated.fasta &>>./meme_output/meme_out94.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LDAVAKTRKVTMAEVIRDEYNPGAEINAVP consolidated.fasta &>>./meme_output/meme_out95.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons AVPVFAQSGDDRYDNVDKMIIKEADVLPHA consolidated.fasta &>>./meme_output/meme_out96.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons DEYNPGAEINAVPVFAQSGDDRYDNVDKMI consolidated.fasta &>>./meme_output/meme_out97.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons RYDNVDKMIIKEADVLPHALINNVEEKLGL consolidated.fasta &>>./meme_output/meme_out98.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons EEKLGLKGEKLLEYVKWLRDRIIKLRVRED consolidated.fasta &>>./meme_output/meme_out99.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons NVDKMIIKEADVLPHALINNVEEKLGLKGE consolidated.fasta &>>./meme_output/meme_out100.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons IKLRVREDYAPIFHIDVYGTIGAAFDVDIK consolidated.fasta &>>./meme_output/meme_out101.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GAAFDVDIKAMADYIQTLAEAAKPFHLRIE consolidated.fasta &>>./meme_output/meme_out102.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons VREDYAPIFHIDVYGTIGAAFDVDIKAMAD consolidated.fasta &>>./meme_output/meme_out103.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons AEAAKPFHLRIEGPMDVEDRQKQMEAMRDL consolidated.fasta &>>./meme_output/meme_out104.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons PFHLRIEGPMDVEDRQKQMEAMRDLRAELD consolidated.fasta &>>./meme_output/meme_out105.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons TLAEAAKPFHLRIEGPMDVEDRQKQMEAMR consolidated.fasta &>>./meme_output/meme_out106.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GPMDVEDRQKQMEAMRDLRAELDGRGVDAE consolidated.fasta &>>./meme_output/meme_out107.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons RAELDGRGVDAELVADEWCNTVEDVKFFTD consolidated.fasta &>>./meme_output/meme_out108.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons PMDVEDRQKQMEAMRDLRAELDGRGVDAEL consolidated.fasta &>>./meme_output/meme_out109.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons CNTVEDVKFFTDNKAGHMVQIKTPDLGGVN consolidated.fasta &>>./meme_output/meme_out110.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons HMVQIKTPDLGGVNNIADAIMYCKANGMGA consolidated.fasta &>>./meme_output/meme_out111.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons VEDVKFFTDNKAGHMVQIKTPDLGGVNNIA consolidated.fasta &>>./meme_output/meme_out112.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons NIADAIMYCKANGMGAYCGGTCNETNRSAE consolidated.fasta &>>./meme_output/meme_out113.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons TCNETNRSAEVTTNIGMACGARQVAAKPGM consolidated.fasta &>>./meme_output/meme_out114.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons YCKANGMGAYCGGTCNETNRSAEVTTNIGM consolidated.fasta &>>./meme_output/meme_out115.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons NIGMACGARQVAAKPGMGVDEGMMIVKNEM consolidated.fasta &>>./meme_output/meme_out116.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons CGARQVAAKPGMGVDEGMMIVKNEMNRVLA consolidated.fasta &>>./meme_output/meme_out117.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons TTNIGMACGARQVAAKPGMGVDEGMMIVKN consolidated.fasta &>>./meme_output/meme_out118.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons AKPGMGVDEGMMIVKNEMNRVLALVGRRKK consolidated.fasta &>>./meme_output/meme_out119.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons HLYAIRLPLRNPFVISYGSYSDMPSIIVKM consolidated.fasta &>>./meme_output/meme_out120.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons MKITAIHLYAIRLPLRNPFVISYGSYSDMP consolidated.fasta &>>./meme_output/meme_out121.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons PFVISYGSYSDMPSIIVKMETDEGIIGYGE consolidated.fasta &>>./meme_output/meme_out122.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons YSDMPSIIVKMETDEGIIGYGEGVADDHVT consolidated.fasta &>>./meme_output/meme_out123.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons FVISYGSYSDMPSIIVKMETDEGIIGYGEG consolidated.fasta &>>./meme_output/meme_out124.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons IVKMETDEGIIGYGEGVADDHVTGESWEST consolidated.fasta &>>./meme_output/meme_out125.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GIIGYGEGVADDHVTGESWESTFHTLKHTL consolidated.fasta &>>./meme_output/meme_out126.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons VKMETDEGIIGYGEGVADDHVTGESWESTF consolidated.fasta &>>./meme_output/meme_out127.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GVADDHVTGESWESTFHTLKHTLTPALIGQ consolidated.fasta &>>./meme_output/meme_out128.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons PMNIEKIHDMMDNTIYGVPTAKAAIDIACF consolidated.fasta &>>./meme_output/meme_out129.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons TLKHTLTPALIGQNPMNIEKIHDMMDNTIY consolidated.fasta &>>./meme_output/meme_out130.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons IYGVPTAKAAIDIACFDIMGKKLNQPVYQL consolidated.fasta &>>./meme_output/meme_out131.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons AAIDIACFDIMGKKLNQPVYQLIGGRYHEE consolidated.fasta &>>./meme_output/meme_out132.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons YGVPTAKAAIDIACFDIMGKKLNQPVYQLI consolidated.fasta &>>./meme_output/meme_out133.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons FDIMGKKLNQPVYQLIGGRYHEEFPVTHVL consolidated.fasta &>>./meme_output/meme_out134.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons NMAEEAASMIQKGYQSFKMKVGTNVKEDVK consolidated.fasta &>>./meme_output/meme_out135.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons HEEFPVTHVLSIADPENMAEEAASMIQKGY consolidated.fasta &>>./meme_output/meme_out136.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons FKMKVGTNVKEDVKRIEAVRERVGNDIAIR consolidated.fasta &>>./meme_output/meme_out137.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons VKEDVKRIEAVRERVGNDIAIRVDVNQGWK consolidated.fasta &>>./meme_output/meme_out138.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons KMKVGTNVKEDVKRIEAVRERVGNDIAIRV consolidated.fasta &>>./meme_output/meme_out139.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons EAVRERVGNDIAIRVDVNQGWKNSANTLTA consolidated.fasta &>>./meme_output/meme_out140.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GWKNSANTLTALRSLGHLNIDWIEQPVIAD consolidated.fasta &>>./meme_output/meme_out141.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GNDIAIRVDVNQGWKNSANTLTALRSLGHL consolidated.fasta &>>./meme_output/meme_out142.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons RSLGHLNIDWIEQPVIADDIDAMAHIRSKT consolidated.fasta &>>./meme_output/meme_out143.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons HIRSKTDLPLMIDEGLKSSREMRQIIKLEA consolidated.fasta &>>./meme_output/meme_out144.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons WIEQPVIADDIDAMAHIRSKTDLPLMIDEG consolidated.fasta &>>./meme_output/meme_out145.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LKSSREMRQIIKLEAADKVNIKLMKCGGIY consolidated.fasta &>>./meme_output/meme_out146.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons DKVNIKLMKCGGIYPAVKLAHQAEMAGIEC consolidated.fasta &>>./meme_output/meme_out147.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons SREMRQIIKLEAADKVNIKLMKCGGIYPAV consolidated.fasta &>>./meme_output/meme_out148.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons PAVKLAHQAEMAGIECQVGSMVESSVASSA consolidated.fasta &>>./meme_output/meme_out149.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons VGSMVESSVASSAGFHVAFSKKIITSVELT consolidated.fasta &>>./meme_output/meme_out150.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LAHQAEMAGIECQVGSMVESSVASSAGFHV consolidated.fasta &>>./meme_output/meme_out151.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GFHVAFSKKIITSVELTGPLKFTKDIGNLH consolidated.fasta &>>./meme_output/meme_out152.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons IITSVELTGPLKFTKDIGNLHYDVPFIRLN consolidated.fasta &>>./meme_output/meme_out153.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons HVAFSKKIITSVELTGPLKFTKDIGNLHYD consolidated.fasta &>>./meme_output/meme_out154.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons TGPLKFTKDIGNLHYDVPFIRLNEKPGLGI consolidated.fasta &>>./meme_output/meme_out155.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons TKDIGNLHYDVPFIRLNEKPGLGIEINEDT consolidated.fasta &>>./meme_output/meme_out156.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons SVELTGPLKFTKDIGNLHYDVPFIRLNEKP consolidated.fasta &>>./meme_output/meme_out157.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons FIRLNEKPGLGIEINEDTLQELTVFQDIVR consolidated.fasta &>>./meme_output/meme_out158.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons AGGGDYHDQGANHWIDDHIATPMSKYRDYE consolidated.fasta &>>./meme_output/meme_out159.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons MTLPKIKQVRAWFTGGATAEKGAGGGDYHD consolidated.fasta &>>./meme_output/meme_out160.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons MSKYRDYEQLRQSFGINVLGTLVVEVEAEN consolidated.fasta &>>./meme_output/meme_out161.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GINVLGTLVVEVEAENGQTGFAVSTAGEMG consolidated.fasta &>>./meme_output/meme_out162.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons DYEQLRQSFGINVLGTLVVEVEAENGQTGF consolidated.fasta &>>./meme_output/meme_out163.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons EVEAENGQTGFAVSTAGEMGCFIVEKHLNR consolidated.fasta &>>./meme_output/meme_out164.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons KHLNRFIEGKCVSDIKLIHDQMLNATLYYS consolidated.fasta &>>./meme_output/meme_out165.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons AENGQTGFAVSTAGEMGCFIVEKHLNRFIE consolidated.fasta &>>./meme_output/meme_out166.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LNATLYYSGSGGLVMNTISCVDLALWDLFG consolidated.fasta &>>./meme_output/meme_out167.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons TISCVDLALWDLFGKVVGLPVYKLLGGAVR consolidated.fasta &>>./meme_output/meme_out168.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons SGGLVMNTISCVDLALWDLFGKVVGLPVYK consolidated.fasta &>>./meme_output/meme_out169.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons ALWDLFGKVVGLPVYKLLGGAVRDEIQFYA consolidated.fasta &>>./meme_output/meme_out170.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons AVRDEIQFYATGARPDLAKEMGFIGGKMPT consolidated.fasta &>>./meme_output/meme_out171.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons PVYKLLGGAVRDEIQFYATGARPDLAKEMG consolidated.fasta &>>./meme_output/meme_out172.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons YATGARPDLAKEMGFIGGKMPTHWGPHDGD consolidated.fasta &>>./meme_output/meme_out173.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GKMPTHWGPHDGDAGIRKDAAMVADMREKC consolidated.fasta &>>./meme_output/meme_out174.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons YATGARPDLAKEMGFIGGKMPTHWGPHDGD consolidated.fasta &>>./meme_output/meme_out175.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons DAAMVADMREKCGEDFWLMLDCWMSQDVNY consolidated.fasta &>>./meme_output/meme_out176.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons DCWMSQDVNYATKLAHACAPYNLKWIEECL consolidated.fasta &>>./meme_output/meme_out177.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons MREKCGEDFWLMLDCWMSQDVNYATKLAHA consolidated.fasta &>>./meme_output/meme_out178.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LAHACAPYNLKWIEECLPPQQYEGYRELKR consolidated.fasta &>>./meme_output/meme_out179.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons KWIEECLPPQQYEGYRELKRNAPVGMMVTS consolidated.fasta &>>./meme_output/meme_out180.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons TKLAHACAPYNLKWIEECLPPQQYEGYREL consolidated.fasta &>>./meme_output/meme_out181.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GYRELKRNAPVGMMVTSGEHHGTLQSFRTL consolidated.fasta &>>./meme_output/meme_out182.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons SGEHHGTLQSFRTLSETGIDIMQPDVGWCG consolidated.fasta &>>./meme_output/meme_out183.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons KRNAPVGMMVTSGEHHGTLQSFRTLSETGI consolidated.fasta &>>./meme_output/meme_out184.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons TLSETGIDIMQPDVGWCGGLTTLVEIAAIA consolidated.fasta &>>./meme_output/meme_out185.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons MQPDVGWCGGLTTLVEIAAIAKSRGQLVVP consolidated.fasta &>>./meme_output/meme_out186.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons QSFRTLSETGIDIMQPDVGWCGGLTTLVEI consolidated.fasta &>>./meme_output/meme_out187.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons VEIAAIAKSRGQLVVPHGSSVYSHHAVITF consolidated.fasta &>>./meme_output/meme_out188.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GQLVVPHGSSVYSHHAVITFTNTPFSEFLM consolidated.fasta &>>./meme_output/meme_out189.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons EIAAIAKSRGQLVVPHGSSVYSHHAVITFT consolidated.fasta &>>./meme_output/meme_out190.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons VYSHHAVITFTNTPFSEFLMTSPDCSTMRP consolidated.fasta &>>./meme_output/meme_out191.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons TPFSEFLMTSPDCSTMRPQFDPILLNEPVP consolidated.fasta &>>./meme_output/meme_out192.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons YSHHAVITFTNTPFSEFLMTSPDCSTMRPQ consolidated.fasta &>>./meme_output/meme_out193.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons CSTMRPQFDPILLNEPVPVNGRIHKSVLDK consolidated.fasta &>>./meme_output/meme_out194.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons FDPILLNEPVPVNGRIHKSVLDKPGFGVEL consolidated.fasta &>>./meme_output/meme_out195.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons TSPDCSTMRPQFDPILLNEPVPVNGRIHKS consolidated.fasta &>>./meme_output/meme_out196.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons NGRIHKSVLDKPGFGVELNRDCNLKRPYSH consolidated.fasta &>>./meme_output/meme_out197.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons THDVRFPTSRELDGSDAMNPDPDYSAAYVV consolidated.fasta &>>./meme_output/meme_out198.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons MRTIIALETHDVRFPTSRELDGSDAMNPDP consolidated.fasta &>>./meme_output/meme_out199.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons ELDGSDAMNPDPDYSAAYVVLRTDGAEDLA consolidated.fasta &>>./meme_output/meme_out200.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons PDYSAAYVVLRTDGAEDLAGYGLVFTIGRG consolidated.fasta &>>./meme_output/meme_out201.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GSDAMNPDPDYSAAYVVLRTDGAEDLAGYG consolidated.fasta &>>./meme_output/meme_out202.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons VLRTDGAEDLAGYGLVFTIGRGNDVQTAAV consolidated.fasta &>>./meme_output/meme_out203.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons DLAGYGLVFTIGRGNDVQTAAVAALAEHVV consolidated.fasta &>>./meme_output/meme_out204.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LRTDGAEDLAGYGLVFTIGRGNDVQTAAVA consolidated.fasta &>>./meme_output/meme_out205.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons VFTIGRGNDVQTAAVAALAEHVVGLSVDKV consolidated.fasta &>>./meme_output/meme_out206.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons FARRLTNDSQLRWLGPEKGVMHMAIGAVIN consolidated.fasta &>>./meme_output/meme_out207.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons ALAEHVVGLSVDKVIADLGAFARRLTNDSQ consolidated.fasta &>>./meme_output/meme_out208.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons HMAIGAVINAAWDLAARAANKPLWRFIAEL consolidated.fasta &>>./meme_output/meme_out209.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GAVINAAWDLAARAANKPLWRFIAELTPEQ consolidated.fasta &>>./meme_output/meme_out210.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GVMHMAIGAVINAAWDLAARAANKPLWRFI consolidated.fasta &>>./meme_output/meme_out211.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons WDLAARAANKPLWRFIAELTPEQLVDTIDF consolidated.fasta &>>./meme_output/meme_out212.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LTPEQLVDTIDFRYLSDALTRDEALAILRD consolidated.fasta &>>./meme_output/meme_out213.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons AANKPLWRFIAELTPEQLVDTIDFRYLSDA consolidated.fasta &>>./meme_output/meme_out214.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons YLSDALTRDEALAILRDAQPQRAARTATLI consolidated.fasta &>>./meme_output/meme_out215.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons PGWLGYSDEKLVRLAKEAVADGFRTIKLAV consolidated.fasta &>>./meme_output/meme_out216.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons TLIEQGYPAYTTSPGWLGYSDEKLVRLAKE consolidated.fasta &>>./meme_output/meme_out217.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LAKEAVADGFRTIKLAVGANVQDDIRRCRL consolidated.fasta &>>./meme_output/meme_out218.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons TIKLAVGANVQDDIRRCRLARAAIGPDIAM consolidated.fasta &>>./meme_output/meme_out219.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LVRLAKEAVADGFRTIKLAVGANVQDDIRR consolidated.fasta &>>./meme_output/meme_out220.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons RRCRLARAAIGPDIAMAVDANQRWDVGPAI consolidated.fasta &>>./meme_output/meme_out221.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons NQRWDVGPAIDWMRQLAEFDIAWIEEPTSP consolidated.fasta &>>./meme_output/meme_out222.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons AAIGPDIAMAVDANQRWDVGPAIDWMRQLA consolidated.fasta &>>./meme_output/meme_out223.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons RQLAEFDIAWIEEPTSPDDVLGHAAIRQGI consolidated.fasta &>>./meme_output/meme_out224.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons EFDIAWIEEPTSPDDVLGHAAIRQGITPVP consolidated.fasta &>>./meme_output/meme_out225.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons IDWMRQLAEFDIAWIEEPTSPDDVLGHAAI consolidated.fasta &>>./meme_output/meme_out226.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons EPTSPDDVLGHAAIRQGITPVPVSTGEHTQ consolidated.fasta &>>./meme_output/meme_out227.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons AIRQGITPVPVSTGEHTQNRVVFKQLLQAG consolidated.fasta &>>./meme_output/meme_out228.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons WIEEPTSPDDVLGHAAIRQGITPVPVSTGE consolidated.fasta &>>./meme_output/meme_out229.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons TQNRVVFKQLLQAGAVDLIQIDAARVGGVN consolidated.fasta &>>./meme_output/meme_out230.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons QIDAARVGGVNENLAILLLAAKFGVRVFPH consolidated.fasta &>>./meme_output/meme_out231.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons VFKQLLQAGAVDLIQIDAARVGGVNENLAI consolidated.fasta &>>./meme_output/meme_out232.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons AILLLAAKFGVRVFPHAGGVGLCELVQHLA consolidated.fasta &>>./meme_output/meme_out233.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons HAGGVGLCELVQHLAMADFVAITGKMEDRA consolidated.fasta &>>./meme_output/meme_out234.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons AILLLAAKFGVRVFPHAGGVGLCELVQHLA consolidated.fasta &>>./meme_output/meme_out235.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons ADFVAITGKMEDRAIEFVDHLHQHFLDPVR consolidated.fasta &>>./meme_output/meme_out236.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons HQHFLDPVRIQHGRYLAPEVPGFSAEMHPA consolidated.fasta &>>./meme_output/meme_out237.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons EDRAIEFVDHLHQHFLDPVRIQHGRYLAPE consolidated.fasta &>>./meme_output/meme_out238.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GRYLAPEVPGFSAEMHPASIAEFSYPDGRF consolidated.fasta &>>./meme_output/meme_out239.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons EKGALEVLFQGPGYHMSEVLITGLRTRAVN consolidated.fasta &>>./meme_output/meme_out240.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons MASWSHPQFEKGALEVLFQGPGYHMSEVLI consolidated.fasta &>>./meme_output/meme_out241.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GYHMSEVLITGLRTRAVNVPLAYPVHTAVG consolidated.fasta &>>./meme_output/meme_out242.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LITGLRTRAVNVPLAYPVHTAVGTVGTAPL consolidated.fasta &>>./meme_output/meme_out243.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GYHMSEVLITGLRTRAVNVPLAYPVHTAVG consolidated.fasta &>>./meme_output/meme_out244.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons RAVNVPLAYPVHTAVGTVGTAPLVLIDLAT consolidated.fasta &>>./meme_output/meme_out245.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons VGHSYLFAYTPVALKSLKQLLDDMAAMIVN consolidated.fasta &>>./meme_output/meme_out246.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons TVGTAPLVLIDLATSAGVVGHSYLFAYTPV consolidated.fasta &>>./meme_output/meme_out247.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LLDDMAAMIVNEPLAPVSLEAMLAKRFSLA consolidated.fasta &>>./meme_output/meme_out248.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons VSLEAMLAKRFSLAGYTGLIRMAAAGIDMA consolidated.fasta &>>./meme_output/meme_out249.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons VNEPLAPVSLEAMLAKRFSLAGYTGLIRMA consolidated.fasta &>>./meme_output/meme_out250.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons AKRFSLAGYTGLIRMAAAGIDMAAWDALGK consolidated.fasta &>>./meme_output/meme_out251.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GKVHETPLVKLLGANARPVQAYDSHSLDGV consolidated.fasta &>>./meme_output/meme_out252.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons AAGIDMAAWDALGKVHETPLVKLLGANARP consolidated.fasta &>>./meme_output/meme_out253.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GANARPVQAYDSHSLDGVKLATERAVTAAE consolidated.fasta &>>./meme_output/meme_out254.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons DSHSLDGVKLATERAVTAAELGFRAVKTCI consolidated.fasta &>>./meme_output/meme_out255.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons VKLLGANARPVQAYDSHSLDGVKLATERAV consolidated.fasta &>>./meme_output/meme_out256.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons VTAAELGFRAVKTCIGYPALDQDLAVVRSI consolidated.fasta &>>./meme_output/meme_out257.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons DQDLAVVRSIRQAVGDDFGIMVDYNQSLDV consolidated.fasta &>>./meme_output/meme_out258.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons FRAVKTCIGYPALDQDLAVVRSIRQAVGDD consolidated.fasta &>>./meme_output/meme_out259.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons VGDDFGIMVDYNQSLDVPAAIKRSQALQQE consolidated.fasta &>>./meme_output/meme_out260.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons FGIMVDYNQSLDVPAAIKRSQALQQEGVTW consolidated.fasta &>>./meme_output/meme_out261.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons IRQAVGDDFGIMVDYNQSLDVPAAIKRSQA consolidated.fasta &>>./meme_output/meme_out262.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons QSLDVPAAIKRSQALQQEGVTWIEEPTLQH consolidated.fasta &>>./meme_output/meme_out263.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons QALQQEGVTWIEEPTLQHDYEGHQRIQSKL consolidated.fasta &>>./meme_output/meme_out264.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons DYNQSLDVPAAIKRSQALQQEGVTWIEEPT consolidated.fasta &>>./meme_output/meme_out265.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LQHDYEGHQRIQSKLNVPVQMGENWLGPEE consolidated.fasta &>>./meme_output/meme_out266.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons VQMGENWLGPEEMFKALSIGASRLAMPDAM consolidated.fasta &>>./meme_output/meme_out267.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons EGHQRIQSKLNVPVQMGENWLGPEEMFKAL consolidated.fasta &>>./meme_output/meme_out268.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons KALSIGASRLAMPDAMKIGGVTGWIRASAL consolidated.fasta &>>./meme_output/meme_out269.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons AMPDAMKIGGVTGWIRASALAQQFGIPMSS consolidated.fasta &>>./meme_output/meme_out270.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons KALSIGASRLAMPDAMKIGGVTGWIRASAL consolidated.fasta &>>./meme_output/meme_out271.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons VTGWIRASALAQQFGIPMSSHLFQEISAHL consolidated.fasta &>>./meme_output/meme_out272.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons FQEISAHLLAATPTAHWLERLDLAGSVIEP consolidated.fasta &>>./meme_output/meme_out273.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons QQFGIPMSSHLFQEISAHLLAATPTAHWLE consolidated.fasta &>>./meme_output/meme_out274.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons PTAHWLERLDLAGSVIEPTLTFEGGNAVIP consolidated.fasta &>>./meme_output/meme_out275.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons ELRRVQMPLVAPFRTSFGTQSVRELLLLRA consolidated.fasta &>>./meme_output/meme_out276.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons MKLSGVELRRVQMPLVAPFRTSFGTQSVRE consolidated.fasta &>>./meme_output/meme_out277.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons SFGTQSVRELLLLRAVTPAGEGWGECVTMA consolidated.fasta &>>./meme_output/meme_out278.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons TQSVRELLLLRAVTPAGEGWGECVTMAGPL consolidated.fasta &>>./meme_output/meme_out279.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons PFRTSFGTQSVRELLLLRAVTPAGEGWGEC consolidated.fasta &>>./meme_output/meme_out280.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LLRAVTPAGEGWGECVTMAGPLYSSEYNDG consolidated.fasta &>>./meme_output/meme_out281.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons EGWGECVTMAGPLYSSEYNDGAEHVLRHYL consolidated.fasta &>>./meme_output/meme_out282.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons RAVTPAGEGWGECVTMAGPLYSSEYNDGAE consolidated.fasta &>>./meme_output/meme_out283.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons TMAGPLYSSEYNDGAEHVLRHYLIPALLAA consolidated.fasta &>>./meme_output/meme_out284.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons EHVLRHYLIPALLAAEDITAAKVTPLLAKF consolidated.fasta &>>./meme_output/meme_out285.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons SEYNDGAEHVLRHYLIPALLAAEDITAAKV consolidated.fasta &>>./meme_output/meme_out286.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons IPALLAAEDITAAKVTPLLAKFKGHRMAKG consolidated.fasta &>>./meme_output/meme_out287.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons ITAAKVTPLLAKFKGHRMAKGALEMAVLDA consolidated.fasta &>>./meme_output/meme_out288.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons HYLIPALLAAEDITAAKVTPLLAKFKGHRM consolidated.fasta &>>./meme_output/meme_out289.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons KGHRMAKGALEMAVLDAELRAHERSFAAEL consolidated.fasta &>>./meme_output/meme_out290.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GALEMAVLDAELRAHERSFAAELGSVRDSV consolidated.fasta &>>./meme_output/meme_out291.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons KGHRMAKGALEMAVLDAELRAHERSFAAEL consolidated.fasta &>>./meme_output/meme_out292.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LDAELRAHERSFAAELGSVRDSVPCGVSVG consolidated.fasta &>>./meme_output/meme_out293.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons CGVSVGIMDTIPQLLDVVGGYLDEGYVRIK consolidated.fasta &>>./meme_output/meme_out294.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons FAAELGSVRDSVPCGVSVGIMDTIPQLLDV consolidated.fasta &>>./meme_output/meme_out295.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LLDVVGGYLDEGYVRIKLKIEPGWDVEPVR consolidated.fasta &>>./meme_output/meme_out296.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons VRIKLKIEPGWDVEPVRAVRERFGDDVLLQ consolidated.fasta &>>./meme_output/meme_out297.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LLDVVGGYLDEGYVRIKLKIEPGWDVEPVR consolidated.fasta &>>./meme_output/meme_out298.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons EPVRAVRERFGDDVLLQVDANTAYTLGDAP consolidated.fasta &>>./meme_output/meme_out299.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons ANTAYTLGDAPQLARLDPFGLLLIEQPLEE consolidated.fasta &>>./meme_output/meme_out300.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons ERFGDDVLLQVDANTAYTLGDAPQLARLDP consolidated.fasta &>>./meme_output/meme_out301.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons ARLDPFGLLLIEQPLEEEDVLGHAELARRI consolidated.fasta &>>./meme_output/meme_out302.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons ELARRIQTPICLDESIVSARAAADAIKLGA consolidated.fasta &>>./meme_output/meme_out303.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LIEQPLEEEDVLGHAELARRIQTPICLDES consolidated.fasta &>>./meme_output/meme_out304.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons IVSARAAADAIKLGAVQIVNIKPGRVGGYL consolidated.fasta &>>./meme_output/meme_out305.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons IVNIKPGRVGGYLEARRVHDVCAAHGIPVW consolidated.fasta &>>./meme_output/meme_out306.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons RAAADAIKLGAVQIVNIKPGRVGGYLEARR consolidated.fasta &>>./meme_output/meme_out307.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons ARRVHDVCAAHGIPVWCGDMIETGLGRAAN consolidated.fasta &>>./meme_output/meme_out308.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons WCGDMIETGLGRAANVALASLPNFTLPGDT consolidated.fasta &>>./meme_output/meme_out309.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons RVHDVCAAHGIPVWCGDMIETGLGRAANVA consolidated.fasta &>>./meme_output/meme_out310.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons ANVALASLPNFTLPGDTSASDRYYKTDITE consolidated.fasta &>>./meme_output/meme_out311.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons TLPGDTSASDRYYKTDITEPFVLSGGHLPV consolidated.fasta &>>./meme_output/meme_out312.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LASLPNFTLPGDTSASDRYYKTDITEPFVL consolidated.fasta &>>./meme_output/meme_out313.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons ASDRYYKTDITEPFVLSGGHLPVPTGPGLG consolidated.fasta &>>./meme_output/meme_out314.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons TDITEPFVLSGGHLPVPTGPGLGVAPIPEL consolidated.fasta &>>./meme_output/meme_out315.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GDTSASDRYYKTDITEPFVLSGGHLPVPTG consolidated.fasta &>>./meme_output/meme_out316.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GHLPVPTGPGLGVAPIPELLDEVTTAKVWI consolidated.fasta &>>./meme_output/meme_out317.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GAIPFSIPYTKPLRFASGEVHAAEHVLVRV consolidated.fasta &>>./meme_output/meme_out318.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons MKIVAIGAIPFSIPYTKPLRFASGEVHAAE consolidated.fasta &>>./meme_output/meme_out319.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons PLRFASGEVHAAEHVLVRVHTDDGIVGVAE consolidated.fasta &>>./meme_output/meme_out320.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons VHAAEHVLVRVHTDDGIVGVAEAPPRPFTY consolidated.fasta &>>./meme_output/meme_out321.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LRFASGEVHAAEHVLVRVHTDDGIVGVAEA consolidated.fasta &>>./meme_output/meme_out322.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LVRVHTDDGIVGVAEAPPRPFTYGETQTGI consolidated.fasta &>>./meme_output/meme_out323.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GIVGVAEAPPRPFTYGETQTGIVAVIEQYF consolidated.fasta &>>./meme_output/meme_out324.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons VRVHTDDGIVGVAEAPPRPFTYGETQTGIV consolidated.fasta &>>./meme_output/meme_out325.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons APPRPFTYGETQTGIVAVIEQYFAPALIGL consolidated.fasta &>>./meme_output/meme_out326.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons IEQYFAPALIGLTLTEREVAHTRMARTVGN consolidated.fasta &>>./meme_output/meme_out327.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons APPRPFTYGETQTGIVAVIEQYFAPALIGL consolidated.fasta &>>./meme_output/meme_out328.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons VAHTRMARTVGNPTAKAAIDMAMWDALGQS consolidated.fasta &>>./meme_output/meme_out329.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons TAKAAIDMAMWDALGQSLRLSVSEMLGGYT consolidated.fasta &>>./meme_output/meme_out330.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons ARTVGNPTAKAAIDMAMWDALGQSLRLSVS consolidated.fasta &>>./meme_output/meme_out331.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons MAMWDALGQSLRLSVSEMLGGYTDRMRVSH consolidated.fasta &>>./meme_output/meme_out332.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons VSHMLGFDDPVKMVAEAERIRETYGINTFK consolidated.fasta &>>./meme_output/meme_out333.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons VSEMLGGYTDRMRVSHMLGFDDPVKMVAEA consolidated.fasta &>>./meme_output/meme_out334.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons VAEAERIRETYGINTFKVKVGRRPVQLDTA consolidated.fasta &>>./meme_output/meme_out335.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons RRPVQLDTAVVRALRERFGDAIELYVDGNR consolidated.fasta &>>./meme_output/meme_out336.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons IRETYGINTFKVKVGRRPVQLDTAVVRALR consolidated.fasta &>>./meme_output/meme_out337.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons RFGDAIELYVDGNRGWSAAESLRAMREMAD consolidated.fasta &>>./meme_output/meme_out338.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons NRGWSAAESLRAMREMADLDLLFAEELCPA consolidated.fasta &>>./meme_output/meme_out339.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons ERFGDAIELYVDGNRGWSAAESLRAMREMA consolidated.fasta &>>./meme_output/meme_out340.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons REMADLDLLFAEELCPADDVLSRRRLVGQL consolidated.fasta &>>./meme_output/meme_out341.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LFAEELCPADDVLSRRRLVGQLDMPFIADE consolidated.fasta &>>./meme_output/meme_out342.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons RAMREMADLDLLFAEELCPADDVLSRRRLV consolidated.fasta &>>./meme_output/meme_out343.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LSRRRLVGQLDMPFIADESVPTPADVTREV consolidated.fasta &>>./meme_output/meme_out344.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons MPFIADESVPTPADVTREVLGGSATAISIK consolidated.fasta &>>./meme_output/meme_out345.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LSRRRLVGQLDMPFIADESVPTPADVTREV consolidated.fasta &>>./meme_output/meme_out346.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons PADVTREVLGGSATAISIKTARTGFTGSTR consolidated.fasta &>>./meme_output/meme_out347.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons AISIKTARTGFTGSTRVHHLAEGLGLDMVM consolidated.fasta &>>./meme_output/meme_out348.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons ADVTREVLGGSATAISIKTARTGFTGSTRV consolidated.fasta &>>./meme_output/meme_out349.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons STRVHHLAEGLGLDMVMGNQIDGQIGTACT consolidated.fasta &>>./meme_output/meme_out350.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons DGQIGTACTVSFGTAFERTSRHAGELSNFL consolidated.fasta &>>./meme_output/meme_out351.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons EGLGLDMVMGNQIDGQIGTACTVSFGTAFE consolidated.fasta &>>./meme_output/meme_out352.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons AFERTSRHAGELSNFLDMSDDLLTVPLQIS consolidated.fasta &>>./meme_output/meme_out353.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons SRHAGELSNFLDMSDDLLTVPLQISDGQLH consolidated.fasta &>>./meme_output/meme_out354.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GTAFERTSRHAGELSNFLDMSDDLLTVPLQ consolidated.fasta &>>./meme_output/meme_out355.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons SNFLDMSDDLLTVPLQISDGQLHRRPGPGL consolidated.fasta &>>./meme_output/meme_out356.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons DLLTVPLQISDGQLHRRPGPGLGIEIDPDK consolidated.fasta &>>./meme_output/meme_out357.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GELSNFLDMSDDLLTVPLQISDGQLHRRPG consolidated.fasta &>>./meme_output/meme_out358.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons ISDGQLHRRPGPGLGIEIDPDKLAHYRTDN consolidated.fasta &>>./meme_output/meme_out359.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons KVVPVAGHDSMLLNLSGAHGPLFTRNILIL consolidated.fasta &>>./meme_output/meme_out360.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons AATGAPVITDLKVVPVAGHDSMLLNLSGAH consolidated.fasta &>>./meme_output/meme_out361.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LLNLSGAHGPLFTRNILILTDSSGHVGVGE consolidated.fasta &>>./meme_output/meme_out362.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GPLFTRNILILTDSSGHVGVGEVPGGEGIR consolidated.fasta &>>./meme_output/meme_out363.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons MLLNLSGAHGPLFTRNILILTDSSGHVGVG consolidated.fasta &>>./meme_output/meme_out364.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LTDSSGHVGVGEVPGGEGIRKTLEDARHLL consolidated.fasta &>>./meme_output/meme_out365.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons KTLEDARHLLINQSIGNYQSLLNKVRNAFA consolidated.fasta &>>./meme_output/meme_out366.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons EVPGGEGIRKTLEDARHLLINQSIGNYQSL consolidated.fasta &>>./meme_output/meme_out367.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons INQSIGNYQSLLNKVRNAFADRDVGGRGLQ consolidated.fasta &>>./meme_output/meme_out368.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons KVRNAFADRDVGGRGLQTFDLRIAVHAVTA consolidated.fasta &>>./meme_output/meme_out369.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons IGNYQSLLNKVRNAFADRDVGGRGLQTFDL consolidated.fasta &>>./meme_output/meme_out370.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons DVGGRGLQTFDLRIAVHAVTAVESALLDLL consolidated.fasta &>>./meme_output/meme_out371.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons TAVESALLDLLGQHLQVPVAALLGEGQQRD consolidated.fasta &>>./meme_output/meme_out372.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons RIAVHAVTAVESALLDLLGQHLQVPVAALL consolidated.fasta &>>./meme_output/meme_out373.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LDLLGQHLQVPVAALLGEGQQRDAVEMLGY consolidated.fasta &>>./meme_output/meme_out374.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons VGDRNKTDLGYRSEHEADNEWFRLRNKEAL consolidated.fasta &>>./meme_output/meme_out375.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons QRDAVEMLGYLFYVGDRNKTDLGYRSEHEA consolidated.fasta &>>./meme_output/meme_out376.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons EHEADNEWFRLRNKEALTPESVVALAEAAY consolidated.fasta &>>./meme_output/meme_out377.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons ADNEWFRLRNKEALTPESVVALAEAAYDRY consolidated.fasta &>>./meme_output/meme_out378.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GYRSEHEADNEWFRLRNKEALTPESVVALA consolidated.fasta &>>./meme_output/meme_out379.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LRNKEALTPESVVALAEAAYDRYGFKDFKL consolidated.fasta &>>./meme_output/meme_out380.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LTPESVVALAEAAYDRYGFKDFKLKGGVLR consolidated.fasta &>>./meme_output/meme_out381.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons WFRLRNKEALTPESVVALAEAAYDRYGFKD consolidated.fasta &>>./meme_output/meme_out382.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons AEAAYDRYGFKDFKLKGGVLRGEDEIAAVT consolidated.fasta &>>./meme_output/meme_out383.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GGVLRGEDEIAAVTALSERFPDARITLDPN consolidated.fasta &>>./meme_output/meme_out384.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons AAYDRYGFKDFKLKGGVLRGEDEIAAVTAL consolidated.fasta &>>./meme_output/meme_out385.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons ALSERFPDARITLDPNGAWSLKEAVALCRD consolidated.fasta &>>./meme_output/meme_out386.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons PNGAWSLKEAVALCRDQHHVLAYAEDPCGA consolidated.fasta &>>./meme_output/meme_out387.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons SERFPDARITLDPNGAWSLKEAVALCRDQH consolidated.fasta &>>./meme_output/meme_out388.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons CRDQHHVLAYAEDPCGAENGYSGREVMAEF consolidated.fasta &>>./meme_output/meme_out389.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons HVLAYAEDPCGAENGYSGREVMAEFRRSTG consolidated.fasta &>>./meme_output/meme_out390.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons ALCRDQHHVLAYAEDPCGAENGYSGREVMA consolidated.fasta &>>./meme_output/meme_out391.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons DPCGAENGYSGREVMAEFRRSTGLRTATNM consolidated.fasta &>>./meme_output/meme_out392.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons EFRRSTGLRTATNMIATDWRQMGHAIQLQS consolidated.fasta &>>./meme_output/meme_out393.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons PCGAENGYSGREVMAEFRRSTGLRTATNMI consolidated.fasta &>>./meme_output/meme_out394.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons ATDWRQMGHAIQLQSVDIPLADPHFWTMQG consolidated.fasta &>>./meme_output/meme_out395.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LADPHFWTMQGSVRVAQMCNEWGLTWGSHS consolidated.fasta &>>./meme_output/meme_out396.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons MGHAIQLQSVDIPLADPHFWTMQGSVRVAQ consolidated.fasta &>>./meme_output/meme_out397.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons RVAQMCNEWGLTWGSHSNNHFDISLAMFTH consolidated.fasta &>>./meme_output/meme_out398.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GSHSNNHFDISLAMFTHVAAAAPGNITAID consolidated.fasta &>>./meme_output/meme_out399.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons RVAQMCNEWGLTWGSHSNNHFDISLAMFTH consolidated.fasta &>>./meme_output/meme_out400.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons FTHVAAAAPGNITAIDTHWIWQDGQRLTKE consolidated.fasta &>>./meme_output/meme_out401.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons QRLTKEPLQIKGGLVEVPKKPGLGVELDWD consolidated.fasta &>>./meme_output/meme_out402.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons AIDTHWIWQDGQRLTKEPLQIKGGLVEVPK consolidated.fasta &>>./meme_output/meme_out403.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GLVEVPKKPGLGVELDWDALMKAHEVYKSM consolidated.fasta &>>./meme_output/meme_out404.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons MHHHHHHSSGVDLGTENLYFQSMLKIIDAK consolidated.fasta &>>./meme_output/meme_out405.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons MHHHHHHSSGVDLGTENLYFQSMLKIIDAK consolidated.fasta &>>./meme_output/meme_out406.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons VDLGTENLYFQSMLKIIDAKVIVTCPGRNF consolidated.fasta &>>./meme_output/meme_out407.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GTENLYFQSMLKIIDAKVIVTCPGRNFVTL consolidated.fasta &>>./meme_output/meme_out408.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons HSSGVDLGTENLYFQSMLKIIDAKVIVTCP consolidated.fasta &>>./meme_output/meme_out409.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons QSMLKIIDAKVIVTCPGRNFVTLKITTEDG consolidated.fasta &>>./meme_output/meme_out410.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons DGITGVGDATLNGRELSVVSFLQDHMVPSL consolidated.fasta &>>./meme_output/meme_out411.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons KVIVTCPGRNFVTLKITTEDGITGVGDATL consolidated.fasta &>>./meme_output/meme_out412.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons SFLQDHMVPSLIGRDAHQIEDIWQFFYRGS consolidated.fasta &>>./meme_output/meme_out413.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons DIWQFFYRGSYWRGGPVAMTALAAVDMALW consolidated.fasta &>>./meme_output/meme_out414.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons RDAHQIEDIWQFFYRGSYWRGGPVAMTALA consolidated.fasta &>>./meme_output/meme_out415.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons RGSYWRGGPVAMTALAAVDMALWDIKGKVA consolidated.fasta &>>./meme_output/meme_out416.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GLPVYQLLGGACRTGVTVYGHANGETIEDT consolidated.fasta &>>./meme_output/meme_out417.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons DMALWDIKGKVAGLPVYQLLGGACRTGVTV consolidated.fasta &>>./meme_output/meme_out418.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons TGVTVYGHANGETIEDTIAEAVKYKAMGYK consolidated.fasta &>>./meme_output/meme_out419.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons AEAVKYKAMGYKAIRLQTGVPGLASTYGVS consolidated.fasta &>>./meme_output/meme_out420.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GVTVYGHANGETIEDTIAEAVKYKAMGYKA consolidated.fasta &>>./meme_output/meme_out421.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons TGVPGLASTYGVSKDKMFYEPADNDLPTEN consolidated.fasta &>>./meme_output/meme_out422.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons EPADNDLPTENIWSTAKYLNSVPKLFERAR consolidated.fasta &>>./meme_output/meme_out423.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GVPGLASTYGVSKDKMFYEPADNDLPTENI consolidated.fasta &>>./meme_output/meme_out424.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LNSVPKLFERAREVLGWDVHLLHDVHHRLT consolidated.fasta &>>./meme_output/meme_out425.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons EVLGWDVHLLHDVHHRLTPIEAARLGKDLE consolidated.fasta &>>./meme_output/meme_out426.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons KYLNSVPKLFERAREVLGWDVHLLHDVHHR consolidated.fasta &>>./meme_output/meme_out427.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons RLTPIEAARLGKDLEPYRLFWLEDSVPAEN consolidated.fasta &>>./meme_output/meme_out428.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons AENQAGFRLIRQHTTTPLAVGEIFAHVWDA consolidated.fasta &>>./meme_output/meme_out429.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons PYRLFWLEDSVPAENQAGFRLIRQHTTTPL consolidated.fasta &>>./meme_output/meme_out430.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons HTTTPLAVGEIFAHVWDAKQLIEEQLIDYL consolidated.fasta &>>./meme_output/meme_out431.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons EIFAHVWDAKQLIEEQLIDYLRATVLHAGG consolidated.fasta &>>./meme_output/meme_out432.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LIRQHTTTPLAVGEIFAHVWDAKQLIEEQL consolidated.fasta &>>./meme_output/meme_out433.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons EEQLIDYLRATVLHAGGITNLKKIAAFADL consolidated.fasta &>>./meme_output/meme_out434.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GGITNLKKIAAFADLHHVKTGCHGATDLSP consolidated.fasta &>>./meme_output/meme_out435.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons QLIDYLRATVLHAGGITNLKKIAAFADLHH consolidated.fasta &>>./meme_output/meme_out436.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons DLHHVKTGCHGATDLSPVTMAAALHFDMSI consolidated.fasta &>>./meme_output/meme_out437.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons HGATDLSPVTMAAALHFDMSITNFGLQEYM consolidated.fasta &>>./meme_output/meme_out438.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LHHVKTGCHGATDLSPVTMAAALHFDMSIT consolidated.fasta &>>./meme_output/meme_out439.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons TMAAALHFDMSITNFGLQEYMRHTPETDAV consolidated.fasta &>>./meme_output/meme_out440.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LHFDMSITNFGLQEYMRHTPETDAVFPHAY consolidated.fasta &>>./meme_output/meme_out441.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LSPVTMAAALHFDMSITNFGLQEYMRHTPE consolidated.fasta &>>./meme_output/meme_out442.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GLQEYMRHTPETDAVFPHAYTFSDGMLHPG consolidated.fasta &>>./meme_output/meme_out443.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons EAVIVDVPTKRPIQMSITTVHQQSYVIVRV consolidated.fasta &>>./meme_output/meme_out444.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons MKIDAIEAVIVDVPTKRPIQMSITTVHQQS consolidated.fasta &>>./meme_output/meme_out445.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons KRPIQMSITTVHQQSYVIVRVYSEGLVGVG consolidated.fasta &>>./meme_output/meme_out446.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons TVHQQSYVIVRVYSEGLVGVGEGGSVGGPV consolidated.fasta &>>./meme_output/meme_out447.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons RPIQMSITTVHQQSYVIVRVYSEGLVGVGE consolidated.fasta &>>./meme_output/meme_out448.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons VRVYSEGLVGVGEGGSVGGPVWSAECAETI consolidated.fasta &>>./meme_output/meme_out449.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LVGVGEGGSVGGPVWSAECAETIKIIVERY consolidated.fasta &>>./meme_output/meme_out450.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons VRVYSEGLVGVGEGGSVGGPVWSAECAETI consolidated.fasta &>>./meme_output/meme_out451.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons SVGGPVWSAECAETIKIIVERYLAPHLLGT consolidated.fasta &>>./meme_output/meme_out452.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons VERYLAPHLLGTDAFNVSGALQTMARAVTG consolidated.fasta &>>./meme_output/meme_out453.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons SVGGPVWSAECAETIKIIVERYLAPHLLGT consolidated.fasta &>>./meme_output/meme_out454.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons ALQTMARAVTGNASAKAAVEMALLDLKARA consolidated.fasta &>>./meme_output/meme_out455.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons AAVEMALLDLKARALGVSIAELLGGPLRSA consolidated.fasta &>>./meme_output/meme_out456.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons TGNASAKAAVEMALLDLKARALGVSIAELL consolidated.fasta &>>./meme_output/meme_out457.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LDLKARALGVSIAELLGGPLRSAIPIAWTL consolidated.fasta &>>./meme_output/meme_out458.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons WTLASGDTKRDLDSAVEMIERRRHNRFKVK consolidated.fasta &>>./meme_output/meme_out459.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LLGGPLRSAIPIAWTLASGDTKRDLDSAVE consolidated.fasta &>>./meme_output/meme_out460.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons SAVEMIERRRHNRFKVKLGFRSPQDDLIHM consolidated.fasta &>>./meme_output/meme_out461.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons RFKVKLGFRSPQDDLIHMEALSNSLGSKAY consolidated.fasta &>>./meme_output/meme_out462.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LDSAVEMIERRRHNRFKVKLGFRSPQDDLI consolidated.fasta &>>./meme_output/meme_out463.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons IHMEALSNSLGSKAYLRVDVNQAWDEQVAS consolidated.fasta &>>./meme_output/meme_out464.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons NQAWDEQVASVYIPELEALGVELIEQPVGR consolidated.fasta &>>./meme_output/meme_out465.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons NSLGSKAYLRVDVNQAWDEQVASVYIPELE consolidated.fasta &>>./meme_output/meme_out466.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons ELEALGVELIEQPVGRENTQALRRLSDNNR consolidated.fasta &>>./meme_output/meme_out467.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons RLSDNNRVAIMADESLSTLASAFDLARDRS consolidated.fasta &>>./meme_output/meme_out468.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LIEQPVGRENTQALRRLSDNNRVAIMADES consolidated.fasta &>>./meme_output/meme_out469.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LSTLASAFDLARDRSVDVFSLKLCNMGGVS consolidated.fasta &>>./meme_output/meme_out470.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons DVFSLKLCNMGGVSATQKIAAVAEASGIAS consolidated.fasta &>>./meme_output/meme_out471.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LASAFDLARDRSVDVFSLKLCNMGGVSATQ consolidated.fasta &>>./meme_output/meme_out472.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons ATQKIAAVAEASGIASYGGTMLDSTIGTSV consolidated.fasta &>>./meme_output/meme_out473.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons MLDSTIGTSVALQLYSTVPSLPFGCELIGP consolidated.fasta &>>./meme_output/meme_out474.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons VAEASGIASYGGTMLDSTIGTSVALQLYST consolidated.fasta &>>./meme_output/meme_out475.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons YSTVPSLPFGCELIGPFVLADTLSHEPLEI consolidated.fasta &>>./meme_output/meme_out476.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LPFGCELIGPFVLADTLSHEPLEIRDYELQ consolidated.fasta &>>./meme_output/meme_out477.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LYSTVPSLPFGCELIGPFVLADTLSHEPLE consolidated.fasta &>>./meme_output/meme_out478.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons IGPFVLADTLSHEPLEIRDYELQVPTGVGH consolidated.fasta &>>./meme_output/meme_out479.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons DTLSHEPLEIRDYELQVPTGVGHGMTLDED consolidated.fasta &>>./meme_output/meme_out480.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GCELIGPFVLADTLSHEPLEIRDYELQVPT consolidated.fasta &>>./meme_output/meme_out481.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons IRDYELQVPTGVGHGMTLDEDKVRQYARVS consolidated.fasta &>>./meme_output/meme_out482.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons MVKITRLTTYRLPPRWMFLKVETDEGVTGW consolidated.fasta &>>./meme_output/meme_out483.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons MVKITRLTTYRLPPRWMFLKVETDEGVTGW consolidated.fasta &>>./meme_output/meme_out484.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons TTYRLPPRWMFLKVETDEGVTGWGEPVIEG consolidated.fasta &>>./meme_output/meme_out485.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons RLPPRWMFLKVETDEGVTGWGEPVIEGRAR consolidated.fasta &>>./meme_output/meme_out486.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons ITRLTTYRLPPRWMFLKVETDEGVTGWGEP consolidated.fasta &>>./meme_output/meme_out487.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons FLKVETDEGVTGWGEPVIEGRARTVEAAVH consolidated.fasta &>>./meme_output/meme_out488.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LSDYLIGQDPSRINDLWQTMYRAGFYRGGP consolidated.fasta &>>./meme_output/meme_out489.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GEPVIEGRARTVEAAVHELSDYLIGQDPSR consolidated.fasta &>>./meme_output/meme_out490.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons MYRAGFYRGGPILMSAIAGIDQALWDIKGK consolidated.fasta &>>./meme_output/meme_out491.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons IAGIDQALWDIKGKVLGVPVYELLGGLVRD consolidated.fasta &>>./meme_output/meme_out492.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GPILMSAIAGIDQALWDIKGKVLGVPVYEL consolidated.fasta &>>./meme_output/meme_out493.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LWDIKGKVLGVPVYELLGGLVRDKMRTYSW consolidated.fasta &>>./meme_output/meme_out494.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons TYSWVGGDRPADVIAGMKALQAGGFDHFKL consolidated.fasta &>>./meme_output/meme_out495.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons ELLGGLVRDKMRTYSWVGGDRPADVIAGMK consolidated.fasta &>>./meme_output/meme_out496.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons IAGMKALQAGGFDHFKLNGCEEMGIIDTSR consolidated.fasta &>>./meme_output/meme_out497.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons KLNGCEEMGIIDTSRAVDAAVARVAEIRSA consolidated.fasta &>>./meme_output/meme_out498.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons ADVIAGMKALQAGGFDHFKLNGCEEMGIID consolidated.fasta &>>./meme_output/meme_out499.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons AVARVAEIRSAFGNTVEFGLDFHGRVSAPM consolidated.fasta &>>./meme_output/meme_out500.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons FHGRVSAPMAKVLIKELEPYRPLFIEEPVL consolidated.fasta &>>./meme_output/meme_out501.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons RSAFGNTVEFGLDFHGRVSAPMAKVLIKEL consolidated.fasta &>>./meme_output/meme_out502.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons IKELEPYRPLFIEEPVLAEQAETYARLAAH consolidated.fasta &>>./meme_output/meme_out503.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons ARLAAHTHLPIAAGERMFSRFDFKRVLEAG consolidated.fasta &>>./meme_output/meme_out504.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LFIEEPVLAEQAETYARLAAHTHLPIAAGE consolidated.fasta &>>./meme_output/meme_out505.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons RMFSRFDFKRVLEAGGVSILQPDLSHAGGI consolidated.fasta &>>./meme_output/meme_out506.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons QPDLSHAGGITECVKIAAMAEAYDVALAPH consolidated.fasta &>>./meme_output/meme_out507.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons FKRVLEAGGVSILQPDLSHAGGITECVKIA consolidated.fasta &>>./meme_output/meme_out508.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons KIAAMAEAYDVALAPHCPLGPIALAACLHV consolidated.fasta &>>./meme_output/meme_out509.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons DVALAPHCPLGPIALAACLHVDFVSWNATL consolidated.fasta &>>./meme_output/meme_out510.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons ECVKIAAMAEAYDVALAPHCPLGPIALAAC consolidated.fasta &>>./meme_output/meme_out511.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons IALAACLHVDFVSWNATLQEQSMGIHYNKG consolidated.fasta &>>./meme_output/meme_out512.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LDYVRNKADFALEGGYIRPPRLPGLGVDID consolidated.fasta &>>./meme_output/meme_out513.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons SMGIHYNKGAELLDYVRNKADFALEGGYIR consolidated.fasta &>>./meme_output/meme_out514.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GGYIRPPRLPGLGVDIDEALVIERSKEAPD consolidated.fasta &>>./meme_output/meme_out515.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons KEAPDWRNPVWRHADGSVAEWAENLYFQSH consolidated.fasta &>>./meme_output/meme_out516.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons EALVIERSKEAPDWRNPVWRHADGSVAEWA consolidated.fasta &>>./meme_output/meme_out517.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons PVWRHADGSVAEWAENLYFQSHHHHHHWSH consolidated.fasta &>>./meme_output/meme_out518.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons EIVVARLPLKFRFETSFGVQTHKVVPLLIL consolidated.fasta &>>./meme_output/meme_out519.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons HTGRMFKIEAAEIVVARLPLKFRFETSFGV consolidated.fasta &>>./meme_output/meme_out520.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons RFETSFGVQTHKVVPLLILHGEGVQGVAEG consolidated.fasta &>>./meme_output/meme_out521.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons VQTHKVVPLLILHGEGVQGVAEGTMEARPM consolidated.fasta &>>./meme_output/meme_out522.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons RFETSFGVQTHKVVPLLILHGEGVQGVAEG consolidated.fasta &>>./meme_output/meme_out523.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LLILHGEGVQGVAEGTMEARPMYREETIAG consolidated.fasta &>>./meme_output/meme_out524.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons QGVAEGTMEARPMYREETIAGALDLLRGTF consolidated.fasta &>>./meme_output/meme_out525.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons ILHGEGVQGVAEGTMEARPMYREETIAGAL consolidated.fasta &>>./meme_output/meme_out526.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons MEARPMYREETIAGALDLLRGTFLPAILGQ consolidated.fasta &>>./meme_output/meme_out527.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LRGTFLPAILGQTFANPEAVSDALGSYRGN consolidated.fasta &>>./meme_output/meme_out528.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons MEARPMYREETIAGALDLLRGTFLPAILGQ consolidated.fasta &>>./meme_output/meme_out529.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons AVSDALGSYRGNRMARAMVEMAAWDLWART consolidated.fasta &>>./meme_output/meme_out530.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons AMVEMAAWDLWARTLGVPLGTLLGGHKEQV consolidated.fasta &>>./meme_output/meme_out531.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons RGNRMARAMVEMAAWDLWARTLGVPLGTLL consolidated.fasta &>>./meme_output/meme_out532.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons WDLWARTLGVPLGTLLGGHKEQVEVGVSLG consolidated.fasta &>>./meme_output/meme_out533.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons VGVSLGIQADCQATVDLVRRHVEQGYRRIK consolidated.fasta &>>./meme_output/meme_out534.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LGTLLGGHKEQVEVGVSLGIQADCQATVDL consolidated.fasta &>>./meme_output/meme_out535.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons TVDLVRRHVEQGYRRIKLKIKPGWDVQPVR consolidated.fasta &>>./meme_output/meme_out536.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons IKLKIKPGWDVQPVRCTREAFPDIRLTVDA consolidated.fasta &>>./meme_output/meme_out537.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LVRRHVEQGYRRIKLKIKPGWDVQPVRCTR consolidated.fasta &>>./meme_output/meme_out538.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons VRCTREAFPDIRLTVDANSAYTLADAGRLR consolidated.fasta &>>./meme_output/meme_out539.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons ANSAYTLADAGRLRQLDEYDLTYIEQPLAW consolidated.fasta &>>./meme_output/meme_out540.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons REAFPDIRLTVDANSAYTLADAGRLRQLDE consolidated.fasta &>>./meme_output/meme_out541.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LRQLDEYDLTYIEQPLAWDDLVDHAELARR consolidated.fasta &>>./meme_output/meme_out542.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons ELARRIRTPLCLDESVASASDARKALALGA consolidated.fasta &>>./meme_output/meme_out543.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons YIEQPLAWDDLVDHAELARRIRTPLCLDES consolidated.fasta &>>./meme_output/meme_out544.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons VASASDARKALALGAGGVINLKVARVGGHA consolidated.fasta &>>./meme_output/meme_out545.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons VINLKVARVGGHAESRRVHDVAQSFGAPVW consolidated.fasta &>>./meme_output/meme_out546.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons SDARKALALGAGGVINLKVARVGGHAESRR consolidated.fasta &>>./meme_output/meme_out547.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons SRRVHDVAQSFGAPVWCGGMLESGIGRAHN consolidated.fasta &>>./meme_output/meme_out548.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons WCGGMLESGIGRAHNIHLSTLSNFRLPGDT consolidated.fasta &>>./meme_output/meme_out549.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons RVHDVAQSFGAPVWCGGMLESGIGRAHNIH consolidated.fasta &>>./meme_output/meme_out550.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons HNIHLSTLSNFRLPGDTSSASRYWERDLIQ consolidated.fasta &>>./meme_output/meme_out551.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons RLPGDTSSASRYWERDLIQEPLEAVDGLMP consolidated.fasta &>>./meme_output/meme_out552.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LSTLSNFRLPGDTSSASRYWERDLIQEPLE consolidated.fasta &>>./meme_output/meme_out553.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons SASRYWERDLIQEPLEAVDGLMPVPQGPGT consolidated.fasta &>>./meme_output/meme_out554.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons RDLIQEPLEAVDGLMPVPQGPGTGVTLDRE consolidated.fasta &>>./meme_output/meme_out555.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GDTSSASRYWERDLIQEPLEAVDGLMPVPQ consolidated.fasta &>>./meme_output/meme_out556.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GLMPVPQGPGTGVTLDREFLATVTEAQEEH consolidated.fasta &>>./meme_output/meme_out557.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons VREITKPISSPIRNAYIDFTKMTTSLVAVV consolidated.fasta &>>./meme_output/meme_out558.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons MSVRIVDVREITKPISSPIRNAYIDFTKMT consolidated.fasta &>>./meme_output/meme_out559.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons SSPIRNAYIDFTKMTTSLVAVVTDVVREGK consolidated.fasta &>>./meme_output/meme_out560.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons TSLVAVVTDVVREGKRVVGYGFNSNGRYGQ consolidated.fasta &>>./meme_output/meme_out561.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons SPIRNAYIDFTKMTTSLVAVVTDVVREGKR consolidated.fasta &>>./meme_output/meme_out562.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons KRVVGYGFNSNGRYGQGGLIRERFASRILE consolidated.fasta &>>./meme_output/meme_out563.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons FASRILEADPKKLLNEAGDNLDPDKVWAAM consolidated.fasta &>>./meme_output/meme_out564.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons SNGRYGQGGLIRERFASRILEADPKKLLNE consolidated.fasta &>>./meme_output/meme_out565.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons EAGDNLDPDKVWAAMMINEKPGGHGERSVA consolidated.fasta &>>./meme_output/meme_out566.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons DKVWAAMMINEKPGGHGERSVAVGTIDMAV consolidated.fasta &>>./meme_output/meme_out567.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LLNEAGDNLDPDKVWAAMMINEKPGGHGER consolidated.fasta &>>./meme_output/meme_out568.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons PGGHGERSVAVGTIDMAVWDAVAKIAGKPL consolidated.fasta &>>./meme_output/meme_out569.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GTIDMAVWDAVAKIAGKPLFRLLAERHGVK consolidated.fasta &>>./meme_output/meme_out570.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GERSVAVGTIDMAVWDAVAKIAGKPLFRLL consolidated.fasta &>>./meme_output/meme_out571.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons WDAVAKIAGKPLFRLLAERHGVKANPRVFV consolidated.fasta &>>./meme_output/meme_out572.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GYYYPGKGLSMLRGEMRGYLDRGYNVVKMA consolidated.fasta &>>./meme_output/meme_out573.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GVKANPRVFVYAAGGYYYPGKGLSMLRGEM consolidated.fasta &>>./meme_output/meme_out574.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons EMRGYLDRGYNVVKMAIGGAPIEEDRMRIE consolidated.fasta &>>./meme_output/meme_out575.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons NVVKMAIGGAPIEEDRMRIEAVLEEIGKDA consolidated.fasta &>>./meme_output/meme_out576.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons MLRGEMRGYLDRGYNVVKMAIGGAPIEEDR consolidated.fasta &>>./meme_output/meme_out577.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons RMRIEAVLEEIGKDAQLAVDANGRFNLETG consolidated.fasta &>>./meme_output/meme_out578.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons NGRFNLETGIAYAKMLRDYPLFWYEEVGDP consolidated.fasta &>>./meme_output/meme_out579.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons EEIGKDAQLAVDANGRFNLETGIAYAKMLR consolidated.fasta &>>./meme_output/meme_out580.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons KMLRDYPLFWYEEVGDPLDYALQAALAEFY consolidated.fasta &>>./meme_output/meme_out581.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons FWYEEVGDPLDYALQAALAEFYPGPMATGE consolidated.fasta &>>./meme_output/meme_out582.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons AYAKMLRDYPLFWYEEVGDPLDYALQAALA consolidated.fasta &>>./meme_output/meme_out583.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons ALQAALAEFYPGPMATGENLFSHQDARNLL consolidated.fasta &>>./meme_output/meme_out584.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons FSHQDARNLLRYGGMRPDRDWLQFDCALSY consolidated.fasta &>>./meme_output/meme_out585.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons AEFYPGPMATGENLFSHQDARNLLRYGGMR consolidated.fasta &>>./meme_output/meme_out586.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons MRPDRDWLQFDCALSYGLCEYQRTLEVLKT consolidated.fasta &>>./meme_output/meme_out587.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons DCALSYGLCEYQRTLEVLKTHGWSPSRCIP consolidated.fasta &>>./meme_output/meme_out588.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons RYGGMRPDRDWLQFDCALSYGLCEYQRTLE consolidated.fasta &>>./meme_output/meme_out589.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons EVLKTHGWSPSRCIPHGGHQMSLNIAAGLG consolidated.fasta &>>./meme_output/meme_out590.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons CIPHGGHQMSLNIAAGLGLGGNESYPDLFQ consolidated.fasta &>>./meme_output/meme_out591.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons KTHGWSPSRCIPHGGHQMSLNIAAGLGLGG consolidated.fasta &>>./meme_output/meme_out592.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons SLNIAAGLGLGGNESYPDLFQPYGGFPDGV consolidated.fasta &>>./meme_output/meme_out593.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GGFPDGVRVENGHITMPDLPGIGFEGKSDL consolidated.fasta &>>./meme_output/meme_out594.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons NESYPDLFQPYGGFPDGVRVENGHITMPDL consolidated.fasta &>>./meme_output/meme_out595.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons ENGHITMPDLPGIGFEGKSDLYKEMKALAE consolidated.fasta &>>./meme_output/meme_out596.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons KLSLKRYEYEKPFHITGSVSSESRNVEVEI consolidated.fasta &>>./meme_output/meme_out597.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons MSRIVNVKLSLKRYEYEKPFHITGSVSSES consolidated.fasta &>>./meme_output/meme_out598.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons PFHITGSVSSESRNVEVEIVLESGVKGYGE consolidated.fasta &>>./meme_output/meme_out599.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons SSESRNVEVEIVLESGVKGYGEASPSFRVN consolidated.fasta &>>./meme_output/meme_out600.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons FHITGSVSSESRNVEVEIVLESGVKGYGEA consolidated.fasta &>>./meme_output/meme_out601.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons EVEIVLESGVKGYGEASPSFRVNGERVEAL consolidated.fasta &>>./meme_output/meme_out602.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GVKGYGEASPSFRVNGERVEALLAIENAVR consolidated.fasta &>>./meme_output/meme_out603.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons VEIVLESGVKGYGEASPSFRVNGERVEALL consolidated.fasta &>>./meme_output/meme_out604.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons ASPSFRVNGERVEALLAIENAVREMITGID consolidated.fasta &>>./meme_output/meme_out605.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons RNYARIFEITDRLFGFPSLKAAVQFATLDA consolidated.fasta &>>./meme_output/meme_out606.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons AIENAVREMITGIDVRNYARIFEITDRLFG consolidated.fasta &>>./meme_output/meme_out607.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons PSLKAAVQFATLDALSQELGTQVCYLLGGK consolidated.fasta &>>./meme_output/meme_out608.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons AAVQFATLDALSQELGTQVCYLLGGKRDEI consolidated.fasta &>>./meme_output/meme_out609.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons FGFPSLKAAVQFATLDALSQELGTQVCYLL consolidated.fasta &>>./meme_output/meme_out610.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LDALSQELGTQVCYLLGGKRDEIETDKTVG consolidated.fasta &>>./meme_output/meme_out611.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons DKTVGIDTVENRVKEAKKIFEEGFRVIKIK consolidated.fasta &>>./meme_output/meme_out612.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons YLLGGKRDEIETDKTVGIDTVENRVKEAKK consolidated.fasta &>>./meme_output/meme_out613.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons KEAKKIFEEGFRVIKIKVGENLKEDIEAVE consolidated.fasta &>>./meme_output/meme_out614.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GENLKEDIEAVEEIAKVTRGAKYIVDANMG consolidated.fasta &>>./meme_output/meme_out615.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons KIFEEGFRVIKIKVGENLKEDIEAVEEIAK consolidated.fasta &>>./meme_output/meme_out616.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons KVTRGAKYIVDANMGYTQKEAVEFARAVYQ consolidated.fasta &>>./meme_output/meme_out617.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons MGYTQKEAVEFARAVYQKGIDIAVYEQPVR consolidated.fasta &>>./meme_output/meme_out618.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons AKVTRGAKYIVDANMGYTQKEAVEFARAVY consolidated.fasta &>>./meme_output/meme_out619.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons VYQKGIDIAVYEQPVRREDIEGLKFVRFHS consolidated.fasta &>>./meme_output/meme_out620.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GIDIAVYEQPVRREDIEGLKFVRFHSPFPV consolidated.fasta &>>./meme_output/meme_out621.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons FARAVYQKGIDIAVYEQPVRREDIEGLKFV consolidated.fasta &>>./meme_output/meme_out622.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons QPVRREDIEGLKFVRFHSPFPVAADESART consolidated.fasta &>>./meme_output/meme_out623.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons FVRFHSPFPVAADESARTKFDVMRLVKEEA consolidated.fasta &>>./meme_output/meme_out624.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons VYEQPVRREDIEGLKFVRFHSPFPVAADES consolidated.fasta &>>./meme_output/meme_out625.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons ARTKFDVMRLVKEEAVDYVNIKLMKSGISD consolidated.fasta &>>./meme_output/meme_out626.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons NIKLMKSGISDALAIVEIAESSGLKLMIGC consolidated.fasta &>>./meme_output/meme_out627.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons VMRLVKEEAVDYVNIKLMKSGISDALAIVE consolidated.fasta &>>./meme_output/meme_out628.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons AIVEIAESSGLKLMIGCMGESSLGINQSVH consolidated.fasta &>>./meme_output/meme_out629.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GESSLGINQSVHFALGTGAFEFHDLDSHLM consolidated.fasta &>>./meme_output/meme_out630.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons ESSGLKLMIGCMGESSLGINQSVHFALGTG consolidated.fasta &>>./meme_output/meme_out631.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons ALGTGAFEFHDLDSHLMLKEEVFRGKFIQD consolidated.fasta &>>./meme_output/meme_out632.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons EFHDLDSHLMLKEEVFRGKFIQDGPRMRVK consolidated.fasta &>>./meme_output/meme_out633.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons HFALGTGAFEFHDLDSHLMLKEEVFRGKFI consolidated.fasta &>>./meme_output/meme_out634.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons HDLDSHLMLKEEVFRGKFIQDGPRMRVKDQ consolidated.fasta &>>./meme_output/meme_out635.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons KVVPVAGHDSMLLNLSGAHGPLFTRNILIL consolidated.fasta &>>./meme_output/meme_out636.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons AATGAPVITDLKVVPVAGHDSMLLNLSGAH consolidated.fasta &>>./meme_output/meme_out637.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LLNLSGAHGPLFTRNILILTDSSGHVGVGE consolidated.fasta &>>./meme_output/meme_out638.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GPLFTRNILILTDSSGHVGVGEVPGGEGIR consolidated.fasta &>>./meme_output/meme_out639.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons MLLNLSGAHGPLFTRNILILTDSSGHVGVG consolidated.fasta &>>./meme_output/meme_out640.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LTDSSGHVGVGEVPGGEGIRKTLEDARHLL consolidated.fasta &>>./meme_output/meme_out641.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons KTLEDARHLLINQSIGNYQSLLNKVRNAFA consolidated.fasta &>>./meme_output/meme_out642.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons EVPGGEGIRKTLEDARHLLINQSIGNYQSL consolidated.fasta &>>./meme_output/meme_out643.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons INQSIGNYQSLLNKVRNAFADRDVGGRGLQ consolidated.fasta &>>./meme_output/meme_out644.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons KVRNAFADRDVGGRGLQTFDLRIAVHAVTA consolidated.fasta &>>./meme_output/meme_out645.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons IGNYQSLLNKVRNAFADRDVGGRGLQTFDL consolidated.fasta &>>./meme_output/meme_out646.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons DVGGRGLQTFDLRIAVHAVTAVESALLDLL consolidated.fasta &>>./meme_output/meme_out647.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons TAVESALLDLLGQHLQVPVAALLGEGQQRD consolidated.fasta &>>./meme_output/meme_out648.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons RIAVHAVTAVESALLDLLGQHLQVPVAALL consolidated.fasta &>>./meme_output/meme_out649.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LDLLGQHLQVPVAALLGEGQQRDAVEMLGY consolidated.fasta &>>./meme_output/meme_out650.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons VGDRNKTDLGYRSEHEADNEWFRLRNKEAL consolidated.fasta &>>./meme_output/meme_out651.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons QRDAVEMLGYLFYVGDRNKTDLGYRSEHEA consolidated.fasta &>>./meme_output/meme_out652.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons EHEADNEWFRLRNKEALTPESVVALAEAAY consolidated.fasta &>>./meme_output/meme_out653.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons ADNEWFRLRNKEALTPESVVALAEAAYDRY consolidated.fasta &>>./meme_output/meme_out654.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GYRSEHEADNEWFRLRNKEALTPESVVALA consolidated.fasta &>>./meme_output/meme_out655.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LRNKEALTPESVVALAEAAYDRYGFKDFKL consolidated.fasta &>>./meme_output/meme_out656.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LTPESVVALAEAAYDRYGFKDFKLKGGVLR consolidated.fasta &>>./meme_output/meme_out657.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons WFRLRNKEALTPESVVALAEAAYDRYGFKD consolidated.fasta &>>./meme_output/meme_out658.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons AEAAYDRYGFKDFKLKGGVLRGEDEIAAVT consolidated.fasta &>>./meme_output/meme_out659.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GGVLRGEDEIAAVTALSERFPDARITLDPN consolidated.fasta &>>./meme_output/meme_out660.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons AAYDRYGFKDFKLKGGVLRGEDEIAAVTAL consolidated.fasta &>>./meme_output/meme_out661.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons ALSERFPDARITLDPNGAWSLKEAVALCRD consolidated.fasta &>>./meme_output/meme_out662.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons PNGAWSLKEAVALCRDQHHVLAYAEDPCGA consolidated.fasta &>>./meme_output/meme_out663.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons SERFPDARITLDPNGAWSLKEAVALCRDQH consolidated.fasta &>>./meme_output/meme_out664.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons CRDQHHVLAYAEDPCGAENGYSGREVMAEF consolidated.fasta &>>./meme_output/meme_out665.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons HVLAYAEDPCGAENGYSGREVMAEFRRSTG consolidated.fasta &>>./meme_output/meme_out666.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons ALCRDQHHVLAYAEDPCGAENGYSGREVMA consolidated.fasta &>>./meme_output/meme_out667.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons DPCGAENGYSGREVMAEFRRSTGLRTATNM consolidated.fasta &>>./meme_output/meme_out668.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons EFRRSTGLRTATNMIATDWRQMGHAIQLQS consolidated.fasta &>>./meme_output/meme_out669.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons PCGAENGYSGREVMAEFRRSTGLRTATNMI consolidated.fasta &>>./meme_output/meme_out670.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons ATDWRQMGHAIQLQSVDIPLADPHFWTMQG consolidated.fasta &>>./meme_output/meme_out671.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons LADPHFWTMQGSVRVAQMCNEWGLTWGSHS consolidated.fasta &>>./meme_output/meme_out672.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons MGHAIQLQSVDIPLADPHFWTMQGSVRVAQ consolidated.fasta &>>./meme_output/meme_out673.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons RVAQMCNEWGLTWGSHSNNHFDISLAMFTH consolidated.fasta &>>./meme_output/meme_out674.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GSHSNNHFDISLAMFTHVAAAAPGNITAID consolidated.fasta &>>./meme_output/meme_out675.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons RVAQMCNEWGLTWGSHSNNHFDISLAMFTH consolidated.fasta &>>./meme_output/meme_out676.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons FTHVAAAAPGNITAIDTHWIWQDGQRLTKE consolidated.fasta &>>./meme_output/meme_out677.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons QRLTKEPLQIKGGLVEVPKKPGLGVELDWD consolidated.fasta &>>./meme_output/meme_out678.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons AIDTHWIWQDGQRLTKEPLQIKGGLVEVPK consolidated.fasta &>>./meme_output/meme_out679.txt
meme -text -protein -w 30 -p 8 -nmotifs 1 -cons GLVEVPKKPGLGVELDWDALMKAHEVYKSM consolidated.fasta &>>./meme_output/meme_out680.txt
cd ..
cd ..
